# action.yml
name: 'ASP.NET Core Web Application'
description: 'This action builds ASP.NET Core Web Application'
inputs:
  path:
    description: 'build source path'
    required: true
  configuration:
    description: 'build configuration'
    required: true
    default: 'Release'
  os:
    description: 'build os'
    required: true
    default: 'linux'
  arch:
    description: 'build arch'
    required: true
    default: 'x64'
  framework:
    description: 'build framework'
    required: true
    default: 'net8.0'
outputs:
  path:
    description: 'build target path'
    value: ${{ steps.buildaspnetcoreapp.outputs.path }}
runs:
  using: 'composite'
  steps:
    - name: 'ASP.NET Core Web Application'
      id: buildaspnetcoreapp
      shell: bash
      run: |
        dotnet build ${{ inputs.path }} \
          --configuration ${{ inputs.configuration }} \
          --os ${{ inputs.os }} \
          --arch ${{ inputs.arch }} \
          --framework ${{ inputs.framework }} \
          --self-contained true
        if [ -d ${{ inputs.path }} ]; then
          path=$(pwd)/${{ inputs.path }}
        else
          path=$(pwd)/$(dirname ${{ inputs.path }})
        fi
        ls -l $path
        ls -l $path/bin
        ls -l $path/bin/${{ inputs.configuration }}
        ls -l $path/bin/${{ inputs.configuration }}/${{ inputs.framework }}
        ls -l $path/bin/${{ inputs.configuration }}/${{ inputs.framework }}/${{ inputs.os }}-${{ inputs.arch }}
        echo "path=$path/bin/${{ inputs.configuration }}/${{ inputs.framework }}/${{ inputs.os }}-${{ inputs.arch }}" >> $GITHUB_OUTPUT
